/**
 * DeRegNet REST API
 * DeRegNet REST API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: deregnet@informatik.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeRegNetRestApi);
  }
}(this, function(expect, DeRegNetRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeRegNetRestApi.RunInput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RunInput', function() {
    it('should create an instance of RunInput', function() {
      // uncomment below and update the code to test RunInput
      //var instane = new DeRegNetRestApi.RunInput();
      //expect(instance).to.be.a(DeRegNetRestApi.RunInput);
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new DeRegNetRestApi.RunInput();
      //expect(instance).to.be();
    });

    it('should have the property parameterSetId (base name: "parameter_set_id")', function() {
      // uncomment below and update the code to test the property parameterSetId
      //var instane = new DeRegNetRestApi.RunInput();
      //expect(instance).to.be();
    });

    it('should have the property parameterSet (base name: "parameter_set")', function() {
      // uncomment below and update the code to test the property parameterSet
      //var instane = new DeRegNetRestApi.RunInput();
      //expect(instance).to.be();
    });

    it('should have the property graphId (base name: "graph_id")', function() {
      // uncomment below and update the code to test the property graphId
      //var instane = new DeRegNetRestApi.RunInput();
      //expect(instance).to.be();
    });

    it('should have the property scoreId (base name: "score_id")', function() {
      // uncomment below and update the code to test the property scoreId
      //var instane = new DeRegNetRestApi.RunInput();
      //expect(instance).to.be();
    });

    it('should have the property receptorsId (base name: "receptors_id")', function() {
      // uncomment below and update the code to test the property receptorsId
      //var instane = new DeRegNetRestApi.RunInput();
      //expect(instance).to.be();
    });

    it('should have the property terminalsId (base name: "terminals_id")', function() {
      // uncomment below and update the code to test the property terminalsId
      //var instane = new DeRegNetRestApi.RunInput();
      //expect(instance).to.be();
    });

    it('should have the property root (base name: "root")', function() {
      // uncomment below and update the code to test the property root
      //var instane = new DeRegNetRestApi.RunInput();
      //expect(instance).to.be();
    });

  });

}));
