/**
 * DeRegNet REST API
 * DeRegNet REST API 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: deregnet@informatik.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeRegNetRestApi);
  }
}(this, function(expect, DeRegNetRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeRegNetRestApi.SubgraphInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubgraphInfo', function() {
    it('should create an instance of SubgraphInfo', function() {
      // uncomment below and update the code to test SubgraphInfo
      //var instane = new DeRegNetRestApi.SubgraphInfo();
      //expect(instance).to.be.a(DeRegNetRestApi.SubgraphInfo);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new DeRegNetRestApi.SubgraphInfo();
      //expect(instance).to.be();
    });

    it('should have the property runId (base name: "run_id")', function() {
      // uncomment below and update the code to test the property runId
      //var instane = new DeRegNetRestApi.SubgraphInfo();
      //expect(instance).to.be();
    });

    it('should have the property numNodes (base name: "num_nodes")', function() {
      // uncomment below and update the code to test the property numNodes
      //var instane = new DeRegNetRestApi.SubgraphInfo();
      //expect(instance).to.be();
    });

    it('should have the property numEdges (base name: "num_edges")', function() {
      // uncomment below and update the code to test the property numEdges
      //var instane = new DeRegNetRestApi.SubgraphInfo();
      //expect(instance).to.be();
    });

    it('should have the property optimal (base name: "optimal")', function() {
      // uncomment below and update the code to test the property optimal
      //var instane = new DeRegNetRestApi.SubgraphInfo();
      //expect(instance).to.be();
    });

    it('should have the property optimalityType (base name: "optimality_type")', function() {
      // uncomment below and update the code to test the property optimalityType
      //var instane = new DeRegNetRestApi.SubgraphInfo();
      //expect(instance).to.be();
    });

    it('should have the property root (base name: "root")', function() {
      // uncomment below and update the code to test the property root
      //var instane = new DeRegNetRestApi.SubgraphInfo();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instane = new DeRegNetRestApi.SubgraphInfo();
      //expect(instance).to.be();
    });

  });

}));
