/**
 * DeRegNet REST API
 * DeRegNet REST API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: deregnet@informatik.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeRegNetRestApi);
  }
}(this, function(expect, DeRegNetRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeRegNetRestApi.InfoApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InfoApi', function() {
    describe('graphDocs', function() {
      it('should call graphDocs successfully', function(done) {
        //uncomment below and update the code to test graphDocs
        //instance.graphDocs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('help', function() {
      it('should call help successfully', function(done) {
        //uncomment below and update the code to test help
        //instance.help(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('index', function() {
      it('should call index successfully', function(done) {
        //uncomment below and update the code to test index
        //instance.index(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('infoDocs', function() {
      it('should call infoDocs successfully', function(done) {
        //uncomment below and update the code to test infoDocs
        //instance.infoDocs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('nodesetDocs', function() {
      it('should call nodesetDocs successfully', function(done) {
        //uncomment below and update the code to test nodesetDocs
        //instance.nodesetDocs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('parameterSetDocs', function() {
      it('should call parameterSetDocs successfully', function(done) {
        //uncomment below and update the code to test parameterSetDocs
        //instance.parameterSetDocs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('runDocs', function() {
      it('should call runDocs successfully', function(done) {
        //uncomment below and update the code to test runDocs
        //instance.runDocs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scoreDocs', function() {
      it('should call scoreDocs successfully', function(done) {
        //uncomment below and update the code to test scoreDocs
        //instance.scoreDocs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subgraphDocs', function() {
      it('should call subgraphDocs successfully', function(done) {
        //uncomment below and update the code to test subgraphDocs
        //instance.subgraphDocs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
