# coding: utf-8

# flake8: noqa
"""
    DeRegNet REST API

    DeRegNet REST API   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: deregnet@informatik.uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.graph_info import GraphInfo
from swagger_client.models.inital_graph_info import InitalGraphInfo
from swagger_client.models.node_set import NodeSet
from swagger_client.models.node_set_info import NodeSetInfo
from swagger_client.models.parameter_set import ParameterSet
from swagger_client.models.parameter_set_info import ParameterSetInfo
from swagger_client.models.run_info import RunInfo
from swagger_client.models.run_input import RunInput
from swagger_client.models.score import Score
from swagger_client.models.score_info import ScoreInfo
from swagger_client.models.subgraph_info import SubgraphInfo
