# coding: utf-8

"""
    DeRegNet REST API

    DeRegNet REST API   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: deregnet@informatik.uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

import pprint
import re  # noqa: F401

import six


class ParameterSetInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'id': 'str',
        'start_time': 'str',
        'done': 'bool'
    }

    attribute_map = {
        'description': 'description',
        'id': 'id',
        'start_time': 'start_time',
        'done': 'done'
    }

    def __init__(self, description=None, id=None, start_time=None, done=None):  # noqa: E501
        """ParameterSetInfo - a model defined in Swagger"""  # noqa: E501

        self._description = None
        self._id = None
        self._start_time = None
        self._done = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if id is not None:
            self.id = id
        if start_time is not None:
            self.start_time = start_time
        if done is not None:
            self.done = done

    @property
    def description(self):
        """Gets the description of this ParameterSetInfo.  # noqa: E501

        Description of the run  # noqa: E501

        :return: The description of this ParameterSetInfo.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ParameterSetInfo.

        Description of the run  # noqa: E501

        :param description: The description of this ParameterSetInfo.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this ParameterSetInfo.  # noqa: E501

        Id of the score object  # noqa: E501

        :return: The id of this ParameterSetInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ParameterSetInfo.

        Id of the score object  # noqa: E501

        :param id: The id of this ParameterSetInfo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def start_time(self):
        """Gets the start_time of this ParameterSetInfo.  # noqa: E501

        Time of upload  # noqa: E501

        :return: The start_time of this ParameterSetInfo.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this ParameterSetInfo.

        Time of upload  # noqa: E501

        :param start_time: The start_time of this ParameterSetInfo.  # noqa: E501
        :type: str
        """

        self._start_time = start_time

    @property
    def done(self):
        """Gets the done of this ParameterSetInfo.  # noqa: E501

        Whether the run is completed  # noqa: E501

        :return: The done of this ParameterSetInfo.  # noqa: E501
        :rtype: bool
        """
        return self._done

    @done.setter
    def done(self, done):
        """Sets the done of this ParameterSetInfo.

        Whether the run is completed  # noqa: E501

        :param done: The done of this ParameterSetInfo.  # noqa: E501
        :type: bool
        """

        self._done = done

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ParameterSetInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
