# coding: utf-8

"""
    DeRegNet REST API

    DeRegNet REST API   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: deregnet@informatik.uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.subgraph_api import SubgraphApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubgraphApi(unittest.TestCase):
    """SubgraphApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.subgraph_api.SubgraphApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_subgraph(self):
        """Test case for delete_subgraph

        Delete a previously found subgraph  # noqa: E501
        """
        pass

    def test_download_subgraph_as(self):
        """Test case for download_subgraph_as

        Download a subgraph  # noqa: E501
        """
        pass

    def test_get_subgraph(self):
        """Test case for get_subgraph

        Retrieve the information about a subgraph  # noqa: E501
        """
        pass

    def test_get_subgraphs(self):
        """Test case for get_subgraphs

        List available found subgraphs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
