# coding: utf-8

"""
    DeRegNet REST API

    DeRegNet REST API   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: deregnet@informatik.uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.info_api import InfoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.info_api.InfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_graph_docs(self):
        """Test case for graph_docs

        Help page on graph endpoint  # noqa: E501
        """
        pass

    def test_help(self):
        """Test case for help

        General help page  # noqa: E501
        """
        pass

    def test_index(self):
        """Test case for index

        Index, redirects to /info  # noqa: E501
        """
        pass

    def test_info_docs(self):
        """Test case for info_docs

        Help page on info endpoint  # noqa: E501
        """
        pass

    def test_nodeset_docs(self):
        """Test case for nodeset_docs

        Help page on nodeset endpoint  # noqa: E501
        """
        pass

    def test_parameter_set_docs(self):
        """Test case for parameter_set_docs

        Help page on subgraph endpoint  # noqa: E501
        """
        pass

    def test_run_docs(self):
        """Test case for run_docs

        Help page on run endpoint  # noqa: E501
        """
        pass

    def test_score_docs(self):
        """Test case for score_docs

        Help page on score endpoint  # noqa: E501
        """
        pass

    def test_subgraph_docs(self):
        """Test case for subgraph_docs

        Help page on subgraph endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
