# coding: utf-8

"""
    DeRegNet REST API

    DeRegNet REST API   # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: deregnet@informatik.uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.nodeset_api import NodesetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNodesetApi(unittest.TestCase):
    """NodesetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.nodeset_api.NodesetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_nodeset(self):
        """Test case for delete_nodeset

        Delete a previously uploaded node set  # noqa: E501
        """
        pass

    def test_get_nodeset(self):
        """Test case for get_nodeset

        Retrieve information on a previously uploaded node set  # noqa: E501
        """
        pass

    def test_get_nodesets(self):
        """Test case for get_nodesets

        List available previously uploaded node sets  # noqa: E501
        """
        pass

    def test_post_nodeset(self):
        """Test case for post_nodeset

        Upload a node set for use with DeRegNet algorithms  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
