# coding: utf-8

"""
    DeRegNet REST API

    DeRegNet REST API   # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: deregnet@informatik.uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.run_api import RunApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRunApi(unittest.TestCase):
    """RunApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.run_api.RunApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_run(self):
        """Test case for delete_run

        Cancel an active run, you cannot delete finished runs  # noqa: E501
        """
        pass

    def test_get_run(self):
        """Test case for get_run

        Retrieve the status of a previously submitted run  # noqa: E501
        """
        pass

    def test_get_runs(self):
        """Test case for get_runs

        List current and past runs  # noqa: E501
        """
        pass

    def test_post_run(self):
        """Test case for post_run

        Run average score DeRegNet algorithm  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
