# coding: utf-8

"""
    DeRegNet REST API

    DeRegNet REST API   # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: deregnet@informatik.uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.parameter_set_api import ParameterSetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestParameterSetApi(unittest.TestCase):
    """ParameterSetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.parameter_set_api.ParameterSetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_parameter_set(self):
        """Test case for delete_parameter_set

        Delete a previously uploaded parameter collection  # noqa: E501
        """
        pass

    def test_get_parameter_set(self):
        """Test case for get_parameter_set

        Retrieve information on a previously uploaded score  # noqa: E501
        """
        pass

    def test_get_parameter_set_data(self):
        """Test case for get_parameter_set_data

        Retrieve a parameter collection  # noqa: E501
        """
        pass

    def test_get_parameter_set_default(self):
        """Test case for get_parameter_set_default

        Retrieve the defaul parameter collection  # noqa: E501
        """
        pass

    def test_get_parameter_set_default_data(self):
        """Test case for get_parameter_set_default_data

        Retrieve information on a previously uploaded score  # noqa: E501
        """
        pass

    def test_get_parameter_sets(self):
        """Test case for get_parameter_sets

        List available previously uploaded parameter collections  # noqa: E501
        """
        pass

    def test_post_parameter_set(self):
        """Test case for post_parameter_set

        Upload a parameters collection for use with DeRegNet algorithms  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
