# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NodeSetInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, description: str=None, size: int=None, id: str=None, uploaded: str=None):  # noqa: E501
        """NodeSetInfo - a model defined in Swagger

        :param description: The description of this NodeSetInfo.  # noqa: E501
        :type description: str
        :param size: The size of this NodeSetInfo.  # noqa: E501
        :type size: int
        :param id: The id of this NodeSetInfo.  # noqa: E501
        :type id: str
        :param uploaded: The uploaded of this NodeSetInfo.  # noqa: E501
        :type uploaded: str
        """
        self.swagger_types = {
            'description': str,
            'size': int,
            'id': str,
            'uploaded': str
        }

        self.attribute_map = {
            'description': 'description',
            'size': 'size',
            'id': 'id',
            'uploaded': 'uploaded'
        }

        self._description = description
        self._size = size
        self._id = id
        self._uploaded = uploaded

    @classmethod
    def from_dict(cls, dikt) -> 'NodeSetInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NodeSetInfo of this NodeSetInfo.  # noqa: E501
        :rtype: NodeSetInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """Gets the description of this NodeSetInfo.

        Description of the score  # noqa: E501

        :return: The description of this NodeSetInfo.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this NodeSetInfo.

        Description of the score  # noqa: E501

        :param description: The description of this NodeSetInfo.
        :type description: str
        """

        self._description = description

    @property
    def size(self) -> int:
        """Gets the size of this NodeSetInfo.

        Number of scored nodes  # noqa: E501

        :return: The size of this NodeSetInfo.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this NodeSetInfo.

        Number of scored nodes  # noqa: E501

        :param size: The size of this NodeSetInfo.
        :type size: int
        """

        self._size = size

    @property
    def id(self) -> str:
        """Gets the id of this NodeSetInfo.

        Id of the score object  # noqa: E501

        :return: The id of this NodeSetInfo.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this NodeSetInfo.

        Id of the score object  # noqa: E501

        :param id: The id of this NodeSetInfo.
        :type id: str
        """

        self._id = id

    @property
    def uploaded(self) -> str:
        """Gets the uploaded of this NodeSetInfo.

        Time of upload  # noqa: E501

        :return: The uploaded of this NodeSetInfo.
        :rtype: str
        """
        return self._uploaded

    @uploaded.setter
    def uploaded(self, uploaded: str):
        """Sets the uploaded of this NodeSetInfo.

        Time of upload  # noqa: E501

        :param uploaded: The uploaded of this NodeSetInfo.
        :type uploaded: str
        """

        self._uploaded = uploaded
