version: "3"
services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: deregnet
      MONGO_INITDB_ROOT_PASSWORD: isawesome
    ports:
      - ${MONGO_PORT:-27017}:27017/tcp
  
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: deregnet
      ME_CONFIG_MONGODB_ADMINPASSWORD: isawesome
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081/tcp
