/**
 * DeRegNet REST API
 * DeRegNet REST API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: deregnet@informatik.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The InitalGraphInfo model module.
* @module model/InitalGraphInfo
* @version 1.0.0
*/
export default class InitalGraphInfo {
    /**
    * Constructs a new <code>InitalGraphInfo</code>.
    * @alias module:model/InitalGraphInfo
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>InitalGraphInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InitalGraphInfo} obj Optional instance to populate.
    * @return {module:model/InitalGraphInfo} The populated <code>InitalGraphInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InitalGraphInfo();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('node_id_attr')) {
                obj['node_id_attr'] = ApiClient.convertToType(data['node_id_attr'], 'String');
            }
        }
        return obj;
    }

    /**
    * Description of the graph
    * @member {String} description
    */
    description = undefined;
    /**
    * Name of the graph
    * @member {String} name
    */
    name = undefined;
    /**
    * Node attribute containing node ids
    * @member {String} node_id_attr
    */
    node_id_attr = undefined;








}


