/**
 * DeRegNet REST API
 * DeRegNet REST API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: deregnet@informatik.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The NodeSet model module.
* @module model/NodeSet
* @version 1.0.0
*/
export default class NodeSet {
    /**
    * Constructs a new <code>NodeSet</code>.
    * @alias module:model/NodeSet
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>NodeSet</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NodeSet} obj Optional instance to populate.
    * @return {module:model/NodeSet} The populated <code>NodeSet</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NodeSet();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('nodes')) {
                obj['nodes'] = ApiClient.convertToType(data['nodes'], ['String']);
            }
        }
        return obj;
    }

    /**
    * Description of the node set
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Array.<String>} nodes
    */
    nodes = undefined;








}


