/**
 * DeRegNet REST API
 * DeRegNet REST API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: deregnet@informatik.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ParameterSetInfo model module.
* @module model/ParameterSetInfo
* @version 1.0.0
*/
export default class ParameterSetInfo {
    /**
    * Constructs a new <code>ParameterSetInfo</code>.
    * @alias module:model/ParameterSetInfo
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ParameterSetInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ParameterSetInfo} obj Optional instance to populate.
    * @return {module:model/ParameterSetInfo} The populated <code>ParameterSetInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParameterSetInfo();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'String');
            }
            if (data.hasOwnProperty('done')) {
                obj['done'] = ApiClient.convertToType(data['done'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * Description of the run
    * @member {String} description
    */
    description = undefined;
    /**
    * Id of the score object
    * @member {String} id
    */
    id = undefined;
    /**
    * Time of upload
    * @member {String} start_time
    */
    start_time = undefined;
    /**
    * Whether the run is completed
    * @member {Boolean} done
    */
    done = undefined;








}


