/**
 * DeRegNet REST API
 * DeRegNet REST API 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: deregnet@informatik.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ParameterSetInfo model module.
* @module model/ParameterSetInfo
* @version 0.0.1
*/
export default class ParameterSetInfo {
    /**
    * Constructs a new <code>ParameterSetInfo</code>.
    * @alias module:model/ParameterSetInfo
    * @class
    * @param id {String} Id of the score object
    * @param setParameters {Array.<String>} 
    */

    constructor(id, setParameters) {
        

        
        

        this['id'] = id;this['set_parameters'] = setParameters;

        
    }

    /**
    * Constructs a <code>ParameterSetInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ParameterSetInfo} obj Optional instance to populate.
    * @return {module:model/ParameterSetInfo} The populated <code>ParameterSetInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParameterSetInfo();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('set_parameters')) {
                obj['set_parameters'] = ApiClient.convertToType(data['set_parameters'], ['String']);
            }
        }
        return obj;
    }

    /**
    * Description of the run
    * @member {String} description
    */
    description = undefined;
    /**
    * Id of the score object
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {Array.<String>} set_parameters
    */
    set_parameters = undefined;








}


