/**
 * DeRegNet REST API
 * DeRegNet REST API 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: deregnet@informatik.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import RunInput from './RunInput';





/**
* The RunInfo model module.
* @module model/RunInfo
* @version 0.0.1
*/
export default class RunInfo {
    /**
    * Constructs a new <code>RunInfo</code>.
    * @alias module:model/RunInfo
    * @class
    * @param id {String} Id of the score object
    * @param postTime {String} Time of initial run post
    * @param started {Boolean} Whether the run has already started
    * @param done {Boolean} Whether the run is completed
    * @param runInput {module:model/RunInput} 
    */

    constructor(id, postTime, started, done, runInput) {
        

        
        

        this['id'] = id;this['post_time'] = postTime;this['started'] = started;this['done'] = done;this['run_input'] = runInput;

        
    }

    /**
    * Constructs a <code>RunInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RunInfo} obj Optional instance to populate.
    * @return {module:model/RunInfo} The populated <code>RunInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RunInfo();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('post_time')) {
                obj['post_time'] = ApiClient.convertToType(data['post_time'], 'String');
            }
            if (data.hasOwnProperty('started')) {
                obj['started'] = ApiClient.convertToType(data['started'], 'Boolean');
            }
            if (data.hasOwnProperty('done')) {
                obj['done'] = ApiClient.convertToType(data['done'], 'Boolean');
            }
            if (data.hasOwnProperty('subgraph_ids')) {
                obj['subgraph_ids'] = ApiClient.convertToType(data['subgraph_ids'], ['String']);
            }
            if (data.hasOwnProperty('run_input')) {
                obj['run_input'] = RunInput.constructFromObject(data['run_input']);
            }
        }
        return obj;
    }

    /**
    * Description of the run
    * @member {String} description
    */
    description = undefined;
    /**
    * Id of the score object
    * @member {String} id
    */
    id = undefined;
    /**
    * Time of initial run post
    * @member {String} post_time
    */
    post_time = undefined;
    /**
    * Whether the run has already started
    * @member {Boolean} started
    */
    started = undefined;
    /**
    * Whether the run is completed
    * @member {Boolean} done
    */
    done = undefined;
    /**
    * @member {Array.<String>} subgraph_ids
    */
    subgraph_ids = undefined;
    /**
    * @member {module:model/RunInput} run_input
    */
    run_input = undefined;








}


