/**
 * DeRegNet REST API
 * DeRegNet REST API 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: deregnet@informatik.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Score model module.
* @module model/Score
* @version 0.0.1
*/
export default class Score {
    /**
    * Constructs a new <code>Score</code>.
    * @alias module:model/Score
    * @class
    * @param nodeIds {Array.<String>} 
    * @param scoreValues {Array.<Number>} 
    */

    constructor(nodeIds, scoreValues) {
        

        
        

        this['node_ids'] = nodeIds;this['score_values'] = scoreValues;

        
    }

    /**
    * Constructs a <code>Score</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Score} obj Optional instance to populate.
    * @return {module:model/Score} The populated <code>Score</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Score();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('node_ids')) {
                obj['node_ids'] = ApiClient.convertToType(data['node_ids'], ['String']);
            }
            if (data.hasOwnProperty('score_values')) {
                obj['score_values'] = ApiClient.convertToType(data['score_values'], ['Number']);
            }
        }
        return obj;
    }

    /**
    * Description of the score
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Array.<String>} node_ids
    */
    node_ids = undefined;
    /**
    * @member {Array.<Number>} score_values
    */
    score_values = undefined;








}


