/**
 * DeRegNet REST API
 * DeRegNet REST API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: deregnet@informatik.uni-tuebingen.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ScoreInfo model module.
* @module model/ScoreInfo
* @version 1.0.0
*/
export default class ScoreInfo {
    /**
    * Constructs a new <code>ScoreInfo</code>.
    * @alias module:model/ScoreInfo
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ScoreInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ScoreInfo} obj Optional instance to populate.
    * @return {module:model/ScoreInfo} The populated <code>ScoreInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScoreInfo();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('uploaded')) {
                obj['uploaded'] = ApiClient.convertToType(data['uploaded'], 'String');
            }
        }
        return obj;
    }

    /**
    * Description of the score
    * @member {String} description
    */
    description = undefined;
    /**
    * Number of scored nodes
    * @member {Number} size
    */
    size = undefined;
    /**
    * Id of the score object
    * @member {String} id
    */
    id = undefined;
    /**
    * Time of upload
    * @member {String} uploaded
    */
    uploaded = undefined;








}


