# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from deregnet_rest.models.base_model_ import Model
from deregnet_rest import util


class InitalGraphInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, description: str=None, name: str=None, node_id_attr: str=None):  # noqa: E501
        """InitalGraphInfo - a model defined in Swagger

        :param description: The description of this InitalGraphInfo.  # noqa: E501
        :type description: str
        :param name: The name of this InitalGraphInfo.  # noqa: E501
        :type name: str
        :param node_id_attr: The node_id_attr of this InitalGraphInfo.  # noqa: E501
        :type node_id_attr: str
        """
        self.swagger_types = {
            'description': str,
            'name': str,
            'node_id_attr': str
        }

        self.attribute_map = {
            'description': 'description',
            'name': 'name',
            'node_id_attr': 'node_id_attr'
        }

        self._description = description
        self._name = name
        self._node_id_attr = node_id_attr

    @classmethod
    def from_dict(cls, dikt) -> 'InitalGraphInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InitalGraphInfo of this InitalGraphInfo.  # noqa: E501
        :rtype: InitalGraphInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """Gets the description of this InitalGraphInfo.

        Description of the graph  # noqa: E501

        :return: The description of this InitalGraphInfo.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this InitalGraphInfo.

        Description of the graph  # noqa: E501

        :param description: The description of this InitalGraphInfo.
        :type description: str
        """

        self._description = description

    @property
    def name(self) -> str:
        """Gets the name of this InitalGraphInfo.

        Name of the graph  # noqa: E501

        :return: The name of this InitalGraphInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InitalGraphInfo.

        Name of the graph  # noqa: E501

        :param name: The name of this InitalGraphInfo.
        :type name: str
        """

        self._name = name

    @property
    def node_id_attr(self) -> str:
        """Gets the node_id_attr of this InitalGraphInfo.

        Node attribute containing node ids  # noqa: E501

        :return: The node_id_attr of this InitalGraphInfo.
        :rtype: str
        """
        return self._node_id_attr

    @node_id_attr.setter
    def node_id_attr(self, node_id_attr: str):
        """Sets the node_id_attr of this InitalGraphInfo.

        Node attribute containing node ids  # noqa: E501

        :param node_id_attr: The node_id_attr of this InitalGraphInfo.
        :type node_id_attr: str
        """

        self._node_id_attr = node_id_attr
