version: "3"
services:
  deregnet-api:
    volumes:
      - '../../server:/server'
    ports:
      - ${DEREGNET_PORT:-8080}:8080
    environment:
      DEREGNET_MONGO_USER: ${DEREGNET_MONGO_USER:-deregnet}
      DEREGNET_MONGO_PASSWORD: ${DEREGNET_MONGO_PASSWORD:-isawesome}
