version: '3'
services:
  deregnet-api:
    image: sebwink/deregnet-api:dev
    build: 
      context: ../..
      dockerfile: ./docker/server/Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 8080
    restart: on-failure
