version: "3"
services:
  deregnet-worker:
    image: sebwink/deregnet-worker
    build:
      context: ../..
      dockerfile: ./docker/worker/Dockerfile
    restart: on-failure 
    command: /start_worker.sh --mongo-host mongodb --redis-host redis
