version: "3"
services:
  mongodb:
    image: mongo 
    networks:
      - deregnet
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    #ports:
    #  - '8081:8081'
    networks:
      - deregnet

networks:
  deregnet:
    external: True
