version: "3"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
    healthcheck:  
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}", "-d", "${KONG_PG_DATABASE:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - deregnet 
  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@xxx.xx
      PGADMIN_DEFAULT_PASSWORD: secret
    #ports:
    #  - '8111:80/tcp'
    networks:
      - deregnet

networks:
  deregnet:
    external: True
